### ISSUE TITLE
Do we need other adapters?

### ISSUE THREAD

**Issue by aclowwwn** [fluidtrends/binda#8]
I noticed that we don't have the file compilation that previously was in Rara, and for this reason, Archive tests fail. Will we have more adapters?

**Comment by robipop22** [comment]
The initial file adapter was a general one that was identifying the file's extension and applied the required adapter.
Now we have independent adapters that process different file types. But you need to know before the file type so you know which adapter to use.

And yes we will have more adapters. Did you think of any? Let's open separate issues for each one of them.

**Comment by aclowwwn** [comment]
Ok, one I've bumped into this morning is JS files compiler. Don't think we have it yet, right?

**Comment by robipop22** [comment]
> Ok, one I've bumped into this morning is JS files compiler. Don't think we have it yet, right?

we don't. I'll take care of it.

**Comment by robipop22** [comment]
created #11  and #12

**Comment by robipop22** [comment]
Closing this now. 
if we need other adapters we should open separate issues
